server:
  port: 8761
spring:
  application:
    name: spring-cloud-eureka
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:${server.port}/eureka/
  instance:
    prefer-ip-address: true
